---

- name: Install required packages
  package:
    name: "{{ frontend_packages }}"
    state: latest

- name: Deploy virtualhost configuraion
  template:
    src: nginx-default.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Apply frontend configurations
  service:
    name: nginx
    state: reloaded
