---

# BACKEND SEETUP

- hosts: tag_Name_backend
  gather_facts: true
  become: yes

  roles:
    - backend


# FRONTEND SEETUP

#- hosts: tag_Name_fronted
#  gather_facts: true
#  become: yes
#
#  roles:
#    - frontend
