---

# BACKEND SEETUP

- hosts: tag_Name_backend
  gather_facts: true
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - backend


# FRONTEND SEETUP

- hosts: tag_Name_fronted
  gather_facts: true
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - frontend


# FINAL CHECKS

- hosts: tag_Name_backend
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  tasks:
    - name: Get EC2 facts
      ec2_instance_facts:
      delegate_to: localhost
      connection: local
      tags: test

    - name: Set backend_http_address variable
      set_fact:
        backend_http_address: "{{ ec2_ip_address }}"
      tags: test

      command: "curl -I http://{{ backend_http_address }}:{{ backend_http_port }}/{{ environment_target }}.html"
      register: urlrequest
      tags: test

    - debug: msg="{{ urlrequest.stdout }}"
      tags: debug
