---

# BACKEND SEETUP

- hosts: tag_Name_backend
  gather_facts: true
  become: yes

  pre_tasks:
    - name: Load main set of variables
      include_vars:
        file: "{{ playbook_dir }}/../vars/main.yaml"
    - name: Load environment-specific set of variables
      include_vars:
        file: "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - backend


# FRONTEND SEETUP

#- hosts: tag_Name_fronted
#  gather_facts: true
#  become: yes
#
#  roles:
#    - frontend
