---

# BACKEND SEETUP

- hosts: tag_Name_backend
  gather_facts: true
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - backend


# FRONTEND SEETUP

- hosts: tag_Name_frontend
  gather_facts: true
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - frontend


# FINAL CHECKS

- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"

  tasks:
    - name: GYet marker file from the frontend
      command: "curl -f http://{{ frontend_ip }}/env.html"
      register: httpcheck
      failed_when: httpcheck.rc != 0
      tags: test

    - name: Print environment type from the results of previous step and check the correct environment mark
      debug: msg="{{ httpcheck.stdout }} "
      failed_when: "httpcheck.stdout.find('environment_target') != -1"
      tags: test
