---

# BACKEND SEETUP

- hosts: tag_Name_backend
  gather_facts: true
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - backend


# FRONTEND SEETUP

- hosts: tag_Name_frontend
  gather_facts: true
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yaml"
    - "{{ playbook_dir }}/../vars/{{ environment_target }}.yaml"

  roles:
    - frontend


# FINAL CHECKS

#- hosts: tag_Name_backend
#  gather_facts: true
#
#  tasks:
#    - name: Get EC2 facts
#      ec2_instance_facts:
#      delegate_to: tag_Name_backend
#      tags: debug
